version: 2
updates:
  # uv
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  # GH actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
